### ISSUE TITLE
node.js:134         throw e; // process.nextTick error, or 'error' event on first tick

### ISSUE THREAD

**Issue by london111** [wwidd/wwidd#1]
./start.sh            

gives the following error message:

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: Cannot find module '../../../common/flock/flock-0.1.3'
    at Function._resolveFilename (module.js:317:11)
    at Function._load (module.js:262:25)
    at require (module.js:346:19)
    at Object.<anonymous> (/home/dominic/Downloads/wwidd/server/src/utils/system.js:9:11)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at require (module.js:346:19)
    at Object.<anonymous> (/home/dominic/Downloads/wwidd/server/src/tools/browser.js:5:14)

**Comment by danstocker** [comment]
Did you get this while the JS lib dependencies were in place?

**Comment by london111** [comment]
How do I check this?

I should add that I use ubuntu 11.04 and the wwidd version from the git-repro.

nodejs version is: 0.4.9-1ubuntu3

**Comment by danstocker** [comment]
The contents of the dependency ZIP should be so that you see the following folders right under the wwidd root: /common, /www/jorder, and /www/jquery.

**Comment by london111** [comment]
Ok, thanks, I forgot this... now it works!
