### ISSUE TITLE
Wwidd is not working anymore with the current version of node.js

### ISSUE THREAD

**Issue by Vrakfall** [wwidd/wwidd#14]
As the title says, Wwidd is not working anymore with the current version of node.js.

For 2 reasons, the first one is a bit stupid but...
- With the default nodejs package on ubuntu, the `node` command should be `nodejs` instead.
- I think you're using an old way of writing the requires which generates this error :

```
Error: require.paths is removed. Use node_modules folders, or the NODE_PATH environment variable instead.
    at Function.Object.defineProperty.get (module.js:388:11)
    at Object.<anonymous> (/usr/share/Wwidd/server/src/server.js:5:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

Sorry but I've got no time to debug it myself. I would have done it if that was the case.

Thank you in advance for further debugging.

**Comment by amarcks** [comment]
I am currently having the same issue. Any updates? (running Ubuntu 15.10; required dependencies verified)

**Comment by hlechner** [comment]
Hey guys @Vrakfall @amarcks

I've submitted a new `start.sh` which can solve the problem when there is no `node` but there is `nodejs`.

And it give a better way to diagnose these kind of errors, try it and let me know.
