### ISSUE TITLE
Ubuntu 18.04.1 Error: spawn ifconfig ENOENT

### ISSUE THREAD

**Issue by someitalian123** [wwidd/wwidd#28]
I am unable to get wwidd to start in Ubuntu. I had it working in 18.04.1 before I had a hard drive failure and had to do a fresh install. Here is the output from the terminal.

[OK] Executing wwidd ...
[OK] Node.JS return:

SYSTEM - OS type: linux
DB - switching over to DB: default
DB/default - executing query
TOOL - executing: sqlite3 -header -line ../db/default.sqlite SELECT value FROM system WHERE key = 'version'
TOOL - executing: ifconfig 
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn ifconfig ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by shaenr** [comment]
Use this version The fix is on this fork at this PR
https://github.com/jeanlopes/wwidd
