### ISSUE TITLE
Will not start

### ISSUE THREAD

**Issue by thwaller** [wwidd/wwidd#29]
/home/xxxxxxxxxx/Downloads/Wwidd/server/src/server.js:5
require.paths.unshift('server/src');
                      ^

TypeError: Cannot read property 'unshift' of undefined
    at Object.<anonymous> (/home/xxxxxxxxxx/Downloads/Wwidd/server/src/server.js:5:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

Ubuntu 18.04, all dependencies are satisfied and installed.

**Comment by Pandafuchs** [comment]
I've got the same problem

**Comment by rotj** [comment]
Assuming you're on Windows, you probably have a different version of node.js already installed. You can force wwidd to use its bundled version by editing start.cmd.

Change node.exe to redist\node\node.exe

**Comment by thwaller** [comment]
> Assuming you're on Windows, you probably have a different version of node.js already installed. You can force wwidd to use its bundled version by editing start.cmd.
> 
> Change node.exe to redist\node\node.exe

I am using Ubuntu 18.04, which if not known, is Linux.

**Comment by gueland** [comment]
I am running Linux Mint 20.1 Cinnamon, having the same issue:  Installed all the dependencies.  Still get:
/home/'user'/Wwidd/server/src/server.js:5
require.paths.unshift('server/src');
              ^

TypeError: Cannot read property 'unshift' of undefined
    at Object.<anonymous> (/home/gueland/Wwidd/server/src/server.js:5:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by SanskarP** [comment]
Has anyone been able to find a fix for this?
